### ISSUE TITLE
Getting 'Unable to find game!!: output' after compilation, on run

### ISSUE THREAD

**Issue by pr0te** [thennothinghappened/GMEdit-Constructor#1]
Something to note which may be irrelevant, is that I had to hardcode "x64" in getIgorPath for it to work. The compilation works, but I get that error when it tries to run the game. I can see that no "output" folder is generated in my project directory. Got any clue?

**Comment by thennothinghappened** [comment]
Hey! Just letting you know this should be fixed in `v0.4.0`. I hadn't had a chance to test this plugin on Windows until now, and I've taken the chance today to make some internal changes as well.
