### ISSUE TITLE
Paths passed to Igor are unquoted

### ISSUE THREAD

**Issue by thennothinghappened** [thennothinghappened/GMEdit-Constructor#10]
At the moment Constructor gives arguments to Igor without quoting the values, or escaping spaces... which is an issue if any project happens to have spaces in its file path.

Haven't tested if that actually causes any issues (Igor seems to parse arguments very strangely), but do know that what currently blocks this change is that Igor seems to refuse to launch when a runtime path is quoted.

**Comment by craigtubb57** [comment]
> Haven't tested if that actually causes any issues (Igor seems to parse arguments very strangely), but do know that what currently blocks this change is that Igor seems to refuse to launch when a runtime path is quoted.

Have you tried replacing the spaces with %20 instead? Perhaps that's what Igor prefers.

**Comment by thennothinghappened** [comment]
Possible? It'd be pretty weird though and I've never seen the IDE issue any commands using URL encoding...

Also, to keep you in the loop I've not had time to work on Constructor for a bit now thanks to school. I'll get back on it when I can but no guarantees.

**Comment by craigtubb57** [comment]
> Possible? It'd be pretty weird though and I've never seen the IDE issue any commands using URL encoding...
> 
> Also, to keep you in the loop I've not had time to work on Constructor for a bit now thanks to school. I'll get back on it when I can but no guarantees.

Thought it worth a go :)
And no worries, school comes first!

**Comment by thennothinghappened** [comment]
After giving this another proper look (and fixing `stderr` not actually being read, which was probably making debugging harder in quite a few cases) I realised that Node's `spawn` actually already quotes what its given, so trying to add quotes was really just causing it to escape them, which in turn confused Igor. This is actually a non-issue!
