### ISSUE TITLE
Default paths and search path for Igor are incorrect on Linux

### ISSUE THREAD

**Issue by JellyTale** [thennothinghappened/GMEdit-Constructor#20]
Currently the plugin doesn't work on Linux as far as I can tell.

My runtime directories are all set where you'd expect (/home/user/.local/share/GameMakerStudio2-Beta/Cache/runtimes/), the user data path is a bit more interesting, as this may be wrong (/home/farinata/.local/share/GameMakerStudio2-Beta/User).

Is this a mistake that I'm making, or is Linux just not supported?

**Comment by thennothinghappened** [comment]
Heyo, Linux should be supported in theory but I've never tested it myself. What do you mean by "doesn't work"? Does the plugin not load? Does compilation throw an error? etc.

**Comment by PoshoDev** [comment]
@thennothinghappened I tried setting this up in Ubuntu and I'm stuck exactly where @JellyTale is.

I did set up everything on Windows first just to be sure. And on Linux, I installed GameMaker on my Ubuntu machine from the [official Beta `.deb` file](https://releases.gamemaker.io/release-notes/2024/800) and GameMaker itself works as it should.

I found the Linux-equivalent directories for the Beta Runtimes and User directories (same ones as @JellyTale) and even after restarting GMEdit, the dropdown menu for "Versions" does not display anything despite there being a couple in my Runtimes folder.

![image](https://github.com/user-attachments/assets/87549075-2db0-440a-9734-8715f9943462)

I think what @JellyTale meant by _"the user data path is a bit more interesting, as this may be wrong"_ is that—at least in my case—the User directory is empty even if you sign-in through GameMaker itself. But that's definitely not a GMEdit-Constructor issue.

**Comment by thennothinghappened** [comment]
I reckon there's two issues going on here:
1. users must be stored somewhere else — both in windows and macos the users directory does not live side by side to runtimes.
2. the structure of linux runtime installs must look a bit different, since the way runtimes are indexed by Constructor is to check if Igor exists at a specific path within them.

**Comment by thennothinghappened** [comment]
Ah, try removing `/User`.

**Comment by PoshoDev** [comment]
@thennothinghappened Now a "Dumps" option appears:

![image](https://github.com/user-attachments/assets/a8eefda6-5b1c-4696-8461-235baeddee4b)

The `/Dumps` folder contains these two files:
- `dump_pid`
- `timestamp`

Not sure if this is correct.

I did a search for `Igor` files on my entire machine and these are the results:
```
/home/posho/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.600.0.609/bin/igor/linux/x64/Igor
/home/posho/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1100.0.707/bin/igor/linux/x64/Igor
```
There are inside the same directory as my Beta Runtimes path.

**Comment by thennothinghappened** [comment]
Alright, I've just pushed two commits to `main` which should both no longer pick up `Dumps` as a user, and should make runtimes show up. Still not sure where your user directory lives - if you'd be able to run a search for `license.plist`, that might turn up results.

**Comment by PoshoDev** [comment]
@thennothinghappened Thank you! I pulled the changes and the runtimes _do_ show up!

![image](https://github.com/user-attachments/assets/d92ba77f-e942-49b6-b57c-b8d69e8547ab)

The "User" dropdown now shows nothing. I also looked for any `license.plist` file on my computer and didn't get a single result. I signed out of my Opera account on GameMaker and logged back with my Legacy YoYoGames account just to see if that somehow did anything, but still nothing. The `/User` folder is still empty as well.

**Comment by thennothinghappened** [comment]
Hm, my next guess then would be try opening the IDE, change a setting in preferences, then run a search for `local_settings.json`. I'm not sure what else to look for to identify profiles. If this file does not exist, then profiles must be structured completely differently on Linux for some reason beyond me.

**Comment by PoshoDev** [comment]
Yup, that did the trick!

![image](https://github.com/user-attachments/assets/00fcab42-b9e3-42f7-ac0f-12ead8fdb5de)

Running the search gives me this:
```
/home/posho/.config/GameMakerStudio2-Beta/green.tie.rgm_36623/local_settings.json
/home/posho/.config/GameMakerStudio2-Beta/unknownUser_unknownUserID/local_settings.json
/opt/GameMaker-Beta/aarch64/local_settings.json
/opt/GameMaker-Beta/x86_64/local_settings.json
```

Now it works! Thank you so much!

**Comment by thennothinghappened** [comment]
Cool! I've just gone ahead and made a new release version available, so Linux is now properly supported unless there's any other issues. I'll close this issue now as it was issues with paths, but of course do make a new issue if there's any other problems.

**Comment by PoshoDev** [comment]
Thank you so much! I'll fiddle around this weekend and will let you know if I find anything weird. 👍️
Cheers!
