### ISSUE TITLE
GMAssetCompiler fails?

### ISSUE THREAD

**Issue by ElBananita1** [thennothinghappened/GMEdit-Constructor#8]
I can't compile my game. When I try I get this error:

Options: C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.11.1.160\bin\platform_setting_defaults.json
Options: C:\Users\elban\Desktop\gmedit-editor-windows\local_settings.json
Failed to load Options from C:\Users\elban\Desktop\gmedit-editor-windows\local_settings.json
Setting up the Asset compiler
C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.11.1.160/bin/assetcompiler/windows/x64/GMAssetCompiler.dll exited with non-zero status (-1)

**Comment by thennothinghappened** [comment]
Hm, not much to go off here unfortunately.
```
Options: C:\Users\elban\Desktop\gmedit-editor-windows\local_settings.json
```

This line here though doesn't seem right. It should be trying to load `local_settings.json` from your project's directory, but I'd assume `gmedit-editor-windows` is probably not the name of your project, right?

**Comment by ElBananita1** [comment]
No, it's not :[

**Comment by thennothinghappened** [comment]
Hey, just letting you know I'm reopening this as this is a valid Constructor bug, but I'd need you to be willing to test some things to get it working.

Does your path have spaces in it by chance? Could be related to #10

**Comment by ElBananita1** [comment]
> Hey, just letting you know I'm reopening this as this is a valid Constructor bug, but I'd need you to be willing to test some things to get it working.
> 
> Does your path have spaces in it by chance? Could be related to #10 

Hi, I don't understand what do you mean with "path". My project name doesn't have any spaces!

**Comment by thennothinghappened** [comment]
Hello! It's been a _very_ long time as I've had my hands full with school work. If you're still interested in using Constructor I'd suggest giving [v0.9.4](https://github.com/thennothinghappened/GMEdit-Constructor/releases/tag/v0.9.4) a go as I've fixed it losing Igor's error output. Check the logs again and you should see the actual error going on.

**Comment by thennothinghappened** [comment]
Heyo, as I've not heard back in a long while now and don't have anything to go off of here, I'm closing this issue. If you can reproduce this issue with the latest version, ping me here and I'll re-open it :)
